# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sologist-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bultosapi.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_98bbad5fc01146a681f5d057b7cb50e1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4cb13c99fd924863ba2bf36d51e1ab7b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bultosapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_98bbad5fc01146a681f5d057b7cb50e1 }}/sologist-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sologist-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0b0d26642ecd462995f6b6ced7e142e8 }}
        images: 'bultosapi.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_98bbad5fc01146a681f5d057b7cb50e1 }}/sologist-app:${{ github.sha }}'